config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'

  resources :prototypes, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  resources :tags, only: [:index, :show]
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :Prototype

  mount_uploader :content, PrototypeImageUploader

  enum status: %i(main sub)

  validates :content,
            :status,
            presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :captured_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :users, through: :likes
  has_many :likes, dependent: :destroy
  has_many :tags, through: :tag_prototypes
  has_many :tag_prototypes, dependent: :destroy

  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images
  accepts_nested_attributes_for :tags

  validates :title,
            :catch_copy,
            :concept,
            presence: true

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def set_main_thumbnail
    captured_images.main.first.content
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :prototypes, through: :tag_prototypes
  has_many :tag_prototypes, dependent: :destroy
  validates :name, presence: true
end

app/models/tag_prototype.rb
class TagPrototype < ActiveRecord::Base
  belongs_to :tag
  belongs_to :prototype
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, UserImageUploader

  has_many :prototypes
  has_many :comments
  has_many :prototypes, through: :likes
  has_many :likes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile, :position, :occupation, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :move_to_sign_in

  def new
  end

  def create
    @comment = Comment.create(comment: comment_params[:comment], prototype_id: comment_params[:prototype_id], user_id: current_user.id)
    respond_to do |format|
      format.html {redirect_to prototype_path(params[:prototype_id])}
      format.json
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    # binding.pry
    @comment = Comment.find(params[:id])
    # @comment.update(comment_params)
    @comment.update(update_params)
    respond_to do |format|
      format.html {redirect_to prototype_path(params[:prototype_id])}
      format.json
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy if @comment.user_id == current_user.id
    flash[:notice] = "Delete your comment completed"
    respond_to do |format|
      format.html {redirect_to prototype_path(params[:prototype_id])}
      format.json
    end
  end

  private
  def move_to_sign_in
    redirect_to "/users/sign_in" unless user_signed_in?
  end

  def comment_params
    params.permit(:comment, :prototype_id)
  end

  def update_params
    params.require(:comment).permit(:comment).merge(prototype_id: params[:prototype_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(like_params)
    respond_to do |format|
      format.html {redirect_to prototype_path(id: params[:prototype_id])}
      format.json
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy
    respond_to do |format|
      format.html {redirect_to prototype_path(id: params[:prototype_id])}
      format.json
    end
  end

  private

  def like_params
    params.permit(:prototype_id).merge(user_id: current_user.id)
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: [:show, :edit, :update, :destroy]

  def index
    if params[:sort] == "0"
      prototype_ids = Like.group(:prototype_id).order('count_prototype_id DESC').count(:prototype_id).keys
      @liked_prototypes = prototype_ids.map { |id| Prototype.find(id) }
      @prototypes = Kaminari.paginate_array(@liked_prototypes).page(params[:page]).per(4)
    else
      @prototypes = Prototype.order('created_at DESC').page(params[:page]).per(4)
    end
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
  end

  def create
    @prototype = Prototype.new(prototype_params)
    @prototype.tags << Tag.where(name: params[:tag][:name]).first_or_initialize
    if @prototype.save
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      redirect_to ({ action: :new }), alert: 'New prototype was unsuccessfully created'
    end
  end

  def show
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
    @like = @prototype.likes.where(user_id: current_user.id).first if user_signed_in?
    @tags = @prototype.tags
  end

  def edit
    @main = @prototype.captured_images[0]
    @sub = @prototype.captured_images.where(status: 1)
    @add = @prototype.captured_images.build
    @tags = @prototype.tags
  end

  def update
    # before_tag_list = []
    new_tag_list = []
    # after_tag_list = []

    # @prototype.tags.each do |tag|
    #   before_tag_list << tag.name
    # end

    params[:tags].each do |num, tag|
      new_tag_list << tag[:name]
    end
    # after_tag_list = (before_tag_list + new_tag_list).uniq

    @prototype.tags = []
    new_tag_list.each do |tag_name|
      @prototype.tags << Tag.where(name: tag_name).first_or_initialize unless tag_name ==""
    end
    # Tag.where(name: tag[:name]).first_or_initialize if tag[:name].present?
    # @prototype.tags.uniq

    @prototype.update(prototype_params)
    flash[:notice] = 'Edited prototype was successfully saved'
    redirect_to action: :show
  end

  def destroy
    if @prototype.user_id == current_user.id
      @prototype.destroy
    end
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:id, :content, :status]
    )
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @prototypes = @tag.prototypes.page(params[:page]).per(4)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @prototypes = Prototype.where(user_id: params[:id])
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'Your user infomation was successfully updated'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.haml
.container
  .comment-form
    = form_for @comment, url: {action: 'update'}, html: {id: 'edit_comment'} do |f|
      = f.text_field :comment, name: "comment", placeholder: "コメントする", class: "textbox", value: @comment.comment
      = f.submit "Edit"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" =>  "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>  true
    = javascript_include_tag 'application', 'data-turbolinks-track' =>  true
    = csrf_meta_tags
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"}
    / %script{src: "/javascripts/preview.js", type: "text/javascript"}
  %body
    = render "shared/header"
    = render "shared/messages"
    = yield
    = render "shared/footer"

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date

app/views/prototypes/destroy.html.haml
.container
  %p 削除が完了しました。
  = link_to "トップページに戻る", "/"

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images, @main do |image|
              = image_tag @main.content
              = image.file_field :content
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  - if @sub[i].present?
                    = f.fields_for :captured_images, @sub[i] do |image|
                      = image_tag @sub[i].content
                      = image.file_field :content
                      = image.hidden_field :status, value: "sub"
                  - else
                    = f.fields_for :captured_images, @add do |image|
                      = image_tag ""
                      = image.file_field :content
                      = image.hidden_field :status, value: "sub"
        .col-md-12
          %h4 Tags
          - 3.times do |i|
            - if @tags[i].present?
              = text_field_tag "tags[#{i}][name]", @tags[i].name
            - else
              = text_field_tag "tags[#{i}][name]", "", placeholder: "Input Tag"
            / - if @tags[i].present?
            /   = f.fields_for :tags, @tags[i] do |tag|
            /     = tag.text_field :name, require: true, placeholder: "Input Tag"
            / - else
            /   = f.fields_for :tags do |tag|
            /     = tag.text_field :name, value:"", placeholder: "Input Tag"

      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      = link_to "PROTOTYPES" , "javascript:void(0)", class: "btn btn-default tag-name"
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", prototypes_path(sort: "0"), class:"sort_button", remote: true
        %li.btn-default.btn-popular
          = link_to "Newest", prototypes_path(sort: "1"), class:"sort_button", remote: true
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    .prototypes-list
      = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  = paginate(@prototypes)

app/views/prototypes/index.js.haml
$(".prototypes-list").html("#{j(render partial: 'prototypes/prototype', collection: @prototypes)}");
$(".pagination").html("#{j(paginate(@prototypes))}");

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              %img
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :captured_images do |image|
                    %img
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Tag
          = text_field :tag, :name, require: true, placeholder: "Input Tag"
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
          -if user_signed_in? && current_user.id == @prototype.user_id
            %ul.nav.nav-pills.col-lg-11
              = link_to "EDIT", edit_prototype_path, class: "btn btn-default col-lg-1"
            %ul.nav.nav-pills.col-lg-11
              = link_to "DELETE", "/prototypes/#{@prototype.id}", method: :delete, class: "btn btn-default col-lg-1"
          - if user_signed_in?
            %ul.nav.nav-pills.col-lg-11
              - if @like.present?
                = link_to prototype_like_path(@prototype, @like), method: :delete, id:"like_button" do
                  %svg.svg_icon{"enable-background" => "new -282 407.9 30 26", :id => "レイヤー_1", :space => "preserve", :version => "1.1", :viewbox => "-282 407.9 30 26", :x => "0px", :xmlns => "http://www.w3.org/2000/svg", "xmlns:sketch" => "http://www.bohemiancoding.com/sketch/ns", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "0px", :width => "100px", :height => "100px"}
                    %g#Page-1{"sketch:type" => "MSPage"}
                      %g#PROTOPAGE{"sketch:type" => "MSArtboardGroup", :transform => "translate(-1195.000000, -137.000000)"}
                        %g{"enable-background" => "new    "}
                          %path{:d => "M935.7,545.5c1.5,0,2.9,0.4,4,1.2c1.1,0.8,2,1.8,2.5,3c0.5,1.2,0.7,2.5,0.7,3.8c0,1.3-0.3,2.5-0.9,3.5c-1,1.9-2.7,3.9-5.1,6.1s-4.4,3.9-6.3,5.2l-2.7,1.9c-0.3-0.2-0.7-0.4-1.2-0.8c-0.5-0.3-1.4-1-2.8-2c-1.4-1-2.6-2-3.8-3c-1.1-1-2.3-2.2-3.6-3.5c-1.2-1.4-2.2-2.6-2.8-3.8c-0.6-1-0.9-2.2-0.9-3.5c0-1.3,0.2-2.6,0.7-3.8c0.5-1.2,1.3-2.2,2.4-3c1.1-0.8,2.5-1.2,4.1-1.2c1.4,0,2.6,0.3,3.7,0.8c1.1,0.5,1.9,1.2,2.4,2c0.5,0.8,0.9,1.4,1.2,1.9c0.2,0.5,0.4,0.9,0.5,1.3c0.1-0.4,0.3-0.8,0.5-1.3c0.2-0.5,0.6-1.1,1.2-1.9c0.5-0.8,1.4-1.5,2.4-2C933.1,545.8,934.4,545.5,935.7,545.5z", :fill => "red"}
                %input{name: "like_flag", type: "hidden", value: "1", class: "like_flag", id:"like_flag"}
                %input{name: "like_id", type: "hidden", value: @like.id, class: "like_id", id:"like_id"}

              - else
                = link_to prototype_likes_path(@prototype), method: :post, id: "like_button" do
                  %svg.svg_icon{"enable-background" => "new -282 407.9 30 26", :id => "レイヤー_1", :space => "preserve", :version => "1.1", :viewbox => "-282 407.9 30 26", :x => "0px", :xmlns => "http://www.w3.org/2000/svg", "xmlns:sketch" => "http://www.bohemiancoding.com/sketch/ns", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "0px", :width => "100px", :height => "100px"}
                    %g#Page-1{"sketch:type" => "MSPage"}
                      %g#PROTOPAGE{"sketch:type" => "MSArtboardGroup", :transform => "translate(-1195.000000, -137.000000)"}
                        %g{"enable-background" => "new    "}
                          %path{:d => "M935.7,545.5c1.5,0,2.9,0.4,4,1.2c1.1,0.8,2,1.8,2.5,3c0.5,1.2,0.7,2.5,0.7,3.8c0,1.3-0.3,2.5-0.9,3.5c-1,1.9-2.7,3.9-5.1,6.1s-4.4,3.9-6.3,5.2l-2.7,1.9c-0.3-0.2-0.7-0.4-1.2-0.8c-0.5-0.3-1.4-1-2.8-2c-1.4-1-2.6-2-3.8-3c-1.1-1-2.3-2.2-3.6-3.5c-1.2-1.4-2.2-2.6-2.8-3.8c-0.6-1-0.9-2.2-0.9-3.5c0-1.3,0.2-2.6,0.7-3.8c0.5-1.2,1.3-2.2,2.4-3c1.1-0.8,2.5-1.2,4.1-1.2c1.4,0,2.6,0.3,3.7,0.8c1.1,0.5,1.9,1.2,2.4,2c0.5,0.8,0.9,1.4,1.2,1.9c0.2,0.5,0.4,0.9,0.5,1.3c0.1-0.4,0.3-0.8,0.5-1.3c0.2-0.5,0.6-1.1,1.2-1.9c0.5-0.8,1.4-1.5,2.4-2C933.1,545.8,934.4,545.5,935.7,545.5z", :fill => "#D7D7D7"}
                  %input{name: "like_flag", type: "hidden", value: "0", class: "like_flag", id:"like_flag"}
                  %input{name: "like_id", type: "hidden", value: 0, class: "like_id", id:"like_id"}

              %span#likes_count
                = @prototype.likes.length
              %input{name: "current_user_name", type: "hidden", value: current_user.id, class: 'current_user_id' }
              %input{name: "prototype_id", type: "hidden", value: @prototype.id, class: 'prototype_id' }

  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @tags.each do |tag|
          %li
            = link_to tag.name, tag_path(tag), class: "btn btn-default"
  .comments
    %h4 Comments
    -if @comments
      - @comments.each do |comment|
        .comment
          %strong
            = comment.user.name + " : "
          %span.comment-body
            = comment.comment
          -if user_signed_in? && current_user.id == comment.user_id
            = link_to "Edit", edit_prototype_comment_path(@prototype, comment), class: "edit-comment", "data-comment-id": comment.id, "data-user": comment.user.name
            = link_to "Delete", prototype_comment_path(@prototype, comment), "data-comment-id": comment.id, class: "delete-comment", id: comment.id

  .comment-form
    -if current_user
      = form_for([@prototype, @comment], id: "new_comment") do |f|
        = f.text_field :comment, name: "comment", placeholder: "コメントする", class: "textbox"
        = f.submit "SEND"

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Edit', edit_user_path(current_user)
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default
              = link_to "New Photo", new_prototype_path, style: "color: #337ab7;"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/tags/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      = link_to "TAGS" , "javascript:void(0)", class: "btn btn-default tag-name"
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
      = link_to "VIEW PROTOTYPES", root_path, class: "btn btn-default index-button"

.container.proto-list
  .row
    .tag-list
      - @tags.each do |tag|
        = link_to tag.name, tag_path(tag) , class: "btn btn-default tag-button"


.text-center
  / = paginate(@prototypes)

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      = link_to "TAGGED WITH:#{@tag.name}" , "javascript:void(0)", class: "btn btn-default tag-name"
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", prototypes_path(sort: "0"), class:"sort_button", remote: true
        %li.btn-default.btn-popular
          = link_to "Newest", prototypes_path(sort: "1"), class:"sort_button", remote: true
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    .prototypes-list
      = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  = paginate(@prototypes)

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
              = f.file_field :avatar
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            = @prototypes.length
            %i Projects
        .proto-user
          %span.degree= @user.position
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Occupation
            %p= @user.occupation
.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes